version: '3'

services:
  mongodb:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  flaskapp:
    build: ./src2
    command: >
      bash -c "
        pip install --upgrade pip &&
        pip install accelerate -U &&
        python src2/wait_for_mongodb.py &&
        # pip install huggingface_hub &&
        # python src2/retrain_model.py &&
        python -u src2/app.py 
      "
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis

  worker:
    build: ./src2
    command: rq worker tweets --url redis://redis:6379/0 
    volumes:
      - .:/code
    working_dir: /code/src2
    depends_on:
      - mongodb
      - redis

volumes:
  mongo-data: