version: '3'

services:
  mongodb:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  flaskapp:
    build: ./src2
    command: >
      bash -c "
       pip install --upgrade pip &&
      #  pip install gensim==4.3.1  nltk==3.8.1  &&
        python src2/wait_for_mongodb.py &&
        python  -u src2/app.py
      "
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

volumes:
  mongo-data:
